### ISSUE TITLE
Removal of the debug information from the console output

### ISSUE THREAD

**Issue by ALIENQuake** [Systemcluster/wrappe#2]
**Idea description**
During the launching of the console application, various debug information will be displayed:
```
C:\MinimalApp.exe
startpe 0.0.0 (a3920d6)
MinimalApp

version: ROk3Z1n5
target directory: C:\Users\x\AppData\Local\MinimalApp\ROk3Z1n5
runpath: C:\Users\x\AppData\Local\MinimalApp\ROk3Z1n5\MinimalApp.exe
should verify: 2
should extract: false
payload: 0 directories, 1 files, 0 symlinks (1 total)
payload size: 5960213
reading sections...
verifying files...
current dir: C:\Users\x\Documents\Visual Studio 2019\Projects\MinimalApp
running...
MinimalApp v1.0.0
Press any key.
```
I would like to be able to remove displaying that information so the first console line will be the actuall first line of the output of my app.

**Additional context**
This is actually a bug for my use-case because I need to have specific content for the first line of the output. But since it is a very rare use-case, I reported it as a feature request.

**Comment by Systemcluster** [comment]
Thanks for the suggestion, that option should definitely exist!

**Comment by Systemcluster** [comment]
I added a switch to control the output details in the latest snapshot, passing `-i none` to the packer will suppress any output. The default behavior was also adjusted to only show the first two lines.

**Comment by ALIENQuake** [comment]
So quick! Thank you!
