### ISSUE TITLE
Copy assembly information from the original exe to generated exe

### ISSUE THREAD

**Issue by ALIENQuake** [Systemcluster/wrappe#3]
**Idea description**
Copy assembly information from the original executable file to generated executable. The attached executable should have all assembly information filled.

[Example.zip](https://github.com/Systemcluster/wrappe/files/6697341/Example.zip)

**Comment by ALIENQuake** [comment]
@Systemcluster Hey man, did you stopped developing this tool?

**Comment by Systemcluster** [comment]
@ALIENQuake Hey, I started a new job recently so I didn't have a lot of time to work on my open source projects. I didn't stop developing wrappe per se! 😄 This feature in particular is quite a bit of work, I have had something in-progress for it but it might take a while until I finish it, sorry!

**Comment by ALIENQuake** [comment]
@Systemcluster No problem, I just wanted to know if there is a chance for this feature. If this is a lot of work and you are busy, no worries, take your time.

**Comment by Systemcluster** [comment]
It's been way too long, and you probably don't need it anymore, but all resources from the command executable are now copied to the runner in the new release. Thanks again for the idea!

**Comment by ALIENQuake** [comment]
> It's been way too long, and you probably don't need it anymore, but all resources from the command executable are now copied to the runner in the new release. Thanks again for the idea!

I still needed it and, this is wonderful! Thank you!
