### ISSUE TITLE
Parent process ends before child has completed

### ISSUE THREAD

**Issue by Silic0nS0ldier** [Systemcluster/wrappe#5]
**Bug description**
Wrapper terminates before command completed, leaving it running in the background. Behaves similar a bash command is made to execute in the background by adding `&` at the end of a command.

**Reproduction steps**
Wrap a script which produces a non-zero exit code (time may be a factor while the wrapper finishes up, adding a delay should help is this is the case) and run it. Check the reported exit code.

**Additional context**
Observed on MacOS.

**Comment by Silic0nS0ldier** [comment]
Looks to be a known behaviour. https://doc.rust-lang.org/stable/std/process/struct.Child.html#warning

On Linux there is `exec` which fully replaces the existing process, killing the caller in the process.

On Windows (if I've [read the docs](https://docs.microsoft.com/en-us/windows/win32/procthread/terminating-a-process) right, I almost certainly have not) there is no equivalent to `exec`, however child processes won't be closed until an explicit function is called (e.g. `ExitProcess`) or the past thread in a process terminates.

Best I can tell there isn't anything in Rust standard API which covers this in a cross platform manner. `child.wait()` would technically fix this, but it would also prevent `stdin` usage (it gets killed to eliminate a potential deadlock). There is also `try_wait` but contrary to its name its a non-blocking "are we done yet" check, a loop would be required. Shame `wait` can't be used with `stdin` left alone, it all comes down to [literally one line](https://doc.rust-lang.org/stable/src/std/process.rs.html#1780).

**Comment by Systemcluster** [comment]
Closed by 2a6936a62da90422700b07d4418429fc9a22958c for general behavior and 533ca8be458df5d4df6d8f6fe4fd8b56c0577996 with forking on applicable platforms.
