### ISSUE TITLE
Support invoking command with baked in arguments

### ISSUE THREAD

**Issue by Silic0nS0ldier** [Systemcluster/wrappe#8]
**Idea description**
Languages dependent on a runtime like JS must* be executed in a fashion similar to `node ./main.js`, however as wrappe only accepts a single command (colloquially an executable) it is necessary to have an additional wrapper (e.g. shell script).

It would be nice if this was builtin, particularly as it makes it slightly easier to set up cross compilation. There would need to be some way to refer to the extraction target folder in passed arguments (e.g. value substitution).

*ignoring file extension defaults and shebangs.

**Considered alternatives**
Creating a shell script to inject the necessary arguments. e.g.

```sh
#!/usr/bin/env bash
src_path=`dirname "$0"`
"$src_path/bin/node" "$src/path/main.js" $@
```

I'm fairly sure this pattern has some edge cases.

**Additional context**
Nope

**Comment by Systemcluster** [comment]
It took a while, but support for baked in arguments is now included in the new release. In case you still use wrappe and it doesn't work as expected let me know!
