### ISSUE TITLE
Tried an example but didn't work

### ISSUE THREAD

**Issue by PietJankbal** [Systemcluster/wrappe#9]
**Bug description**

Hi, I tried to wrap one of the vulkan samples but it fails with "./../data not found"

Command used:
wrappe.exe  "c:\vulkan_examples_windows_x64" c:\vulkan_examples_windows_x64\bin\bloom.exe" compressed.exe

**Reproduction steps**
wrappe.exe  "c:\vulkan_examples_windows_x64" c:\vulkan_examples_windows_x64\bin\bloom.exe" compressed.exe

I think it happens because the working directory is not set to  vulkan_examples_windows_x64\bin but I'm not sure about it.

(It does work if I'm in directory vulkan_examples_windows_x64\bin, but not when I;m outside of it, then compressed.exe fails)

For convenience I;ve put up the files I used in
 https://github.com/PietJankbal/Chocolatey-for-wine/raw/main/EXTRAS/vulkan_examples_windows_x64.7z

**Comment by Systemcluster** [comment]
The files aren't available anymore, but I assume `bloom.exe` expected the working directory to be `bin`. That case was indeed not covered by the available `current-dir` option.

I've added additional options for `current-dir` in the new release, including `command` which would set the working directory to `bin` in this case. Thanks for the report and apologies for the late response!

**Comment by PietJankbal** [comment]
Hi, I can confirm it works now. Thanks for the fix!
